before:
  hooks:
    - go mod tidy
builds:
  - id: nve
    main: ./cmd/main.go
    binary: "nve"
    env:
      # - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    flags:
      # needed to enable sqlite's FTS extension
      # - --tags=fts5
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      # - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
archives:
    - replacements:
        darwin: Darwin
        linux: Linux
        windows: Windows
        amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^(?i)wip\b'
      - '^docs:'
      - '^test:'

release:
  draft: true  # do not auto-publish
  github:
    owner: ivan3bx
    name: nve
  header: |
    ## nve release ({{ .Date }})
