FROM golang:1.25

RUN apt-get update && apt-get install -y --no-install-recommends \
    tmux \
    gcc \
    libc6-dev \
    make \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["make", "test"]
